name: SmallAmpCI
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  reponame: ${{github.event.repository.name}}
  
on:
  workflow_dispatch:

jobs:
  TestAmplification:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        portion: [1,2] # the content of array is not important, just the length
    name: Job number ${{ strategy.job-index }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-8.0
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15
      - uses: mabdi/smallamp-action@main
      - run: smallAmpCI 
        shell: bash
        env:
          # you can also use: ${{ matrix.portion }}
          SMALLAMP_PORTION: ${{ strategy.job-index }} 
          SMALLAMP_ALLJOBS: ${{ strategy.job-total }}
  TestAmplificationPush:
    runs-on: ubuntu-latest
    needs: TestAmplification
    steps:
      - uses: actions/checkout@v2
        with:
           fetch-depth: 0
      - run: git checkout -b "SmallAmp-${{github.run_number}}"
        shell: bash
      - uses: hpi-swa/setup-smalltalkCI@v1
        id: smalltalkci
        with:
          smalltalk-version: Pharo64-8.0
      - run: smalltalkci -s ${{ steps.smalltalkci.outputs.smalltalk-version }}
        shell: bash
        timeout-minutes: 15
      - uses: mabdi/smallamp-action@main
      - run: python3 runner.py -r amp -d ${{ env.SMALLTALK_CI_BUILD_BASE }} -p ${{ env.reponame }} > overview-amp.txt
        shell: bash
        working-directory: SMALLAMP_CI_HOME
      - run: python3 runner.py -r sum -d ${{ env.SMALLTALK_CI_BUILD_BASE }} -p ${{ env.reponame }} > overview-sum.txt
        shell: bash
        working-directory: SMALLAMP_CI_HOME
      - uses: actions/upload-artifact@v2
        with:
          name: "smallAmp-overview-${{ env.reponame }}-run${{github.run_number}}"
          path: ${{SMALLAMP_CI_HOME}}/overview-*.txt
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: ${{ env.SMALLTALK_CI_BUILD_BASE }}
      - run: cd smallAmp-results*; find . -name "*.zip" -exec unzip {} \;; mv *.st ..
        shell: bash 
        working-directory: ${{ env.SMALLTALK_CI_BUILD_BASE }}
      - run: curl https://raw.githubusercontent.com/mabdi/small-amp/master/scripts/installer.st -o installer.st
        shell: bash 
        working-directory: ${{ env.SMALLTALK_CI_BUILD_BASE }}
      - run: ${{ env.SMALLTALK_CI_VM }} TravisCI.image st --save --quit installer.st
        shell: bash
        working-directory: ${{ env.SMALLTALK_CI_BUILD_BASE }}
      - run: git status
        shell: bash  
      - run: git branch 
        shell: bash
      - run: |
          git config user.name mabdi
          git add '*.st'
          git commit -m '[SmallAmp] amplified tests added'
          git push -u origin HEAD
      - uses: actions/github-script@v4
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.create({
                owner: "mabdi",
                repo: '${{ env.reponame }}',
                title: "[SmallAmp] amplified tests for action number ${{github.run_number}}",
                head: "SmallAmp-${{github.run_number}}",
                base: "${{ github.base_ref }}",
                body: "I submit this pull request to suggest new tests based on the output of SmallAmp tool."
            });
